backstory = (
    'From a strict monastery',
    'Main purpose in life is to influence a band of heroes to fulfill a prophecy',
    'Names every piece of their gear',
    'Has a pet rock',
    'Wants everyone to like them',
    'Is in way too deep with the wrong sort of people',
    'Lost their sense of smell in a bar fight',
    'Always gives the bad news first',
    'Lost their shadow in a bet',
    'Doesn\'t speak a word of common',
    'Has a burning hatred for pirates',
    'Has a bounty on it\'s head',
    'Adds a notch to their sword every night',
    'Can\'t swim',
    'Never turns the other cheek',
    'Woke up in a bar with no memory and a sealed letter',
    'Is trying to avoid a prophecy',
    'Has always wanted to open their own tavern',
    'Won a duel they were supposed to lose out of sheer luck',
    'Is really good at bribing officials',
    'Bangs on about their genealogy to everyone',
    'Killed their brother in a duel over their inheritance',
    'Has a huge debt to pay back',
    'Wants to become a famous singer',
    'Carries the scars of an attempted suicide',
    'Is being hunted by a terrible monster',
    'Wants to one day own their own ship',
    'Has never been kissed',
    'Can\'t stand the sight of blood',
    'Was told they\'ll never be good enough',
    'Is secretly fond of embroidery',
    'Is absolutely astonished by jugglers',
    'Cut from their dead mother\'s womb',
    'Has had it up to here with everyone\'s crap',
    'Hates to be clean',
    'From the strongest family heritage line in the land',
    'Is writing an autobiography',
    'Can\'t stand silence',
    'Has delusions of grandeur',
    'Was expelled from the Royal Guard',
    'Only became an adventurer after losing a bet',
    'Used to live on a volcano',
    'Has a poem for all occasions',
    'Has gotten away with murder',
    'Refuses to admit they\'re past their prime',
    'Once lived on an island that can\'t be reached by boat',
    'Only has two more years before a demon comes back to claim their soul',
    'Is quick to take credit and assign blame',
    'Doesn\'t know their own strength',
    'Part of the Grave Diggers Union',
    'Is running from a marriage arranged by their parents',
    'Owner of the worst brother in town',
    'Mistrusts anyone smaller than them',
    'Once spend 4 months on a floating shanty',
    'Tries to be a friend to everyone',
    'Lost minor appendages due to their gambling addiction',
    'Inspector for the Quality Control for Potions Association',
    'Takes great delight in identifying new beetle species',
    'Never returned anything they borrowed',
    'Always refers to inanimate objects as \'she\'',
    'Is convinced they\'re always being left out',
    'Is afraid of sharp edges',
    'doesn\'t have a reflection',
    'Is searching for the perfect culinary dish',
    'Studied interior dungeon design',
    'Is in a local street gang',
    'Is haunted by the ghosts of those they kill',
    'Lived in a refugee camp for war orphans for a year',
    'Suffers from night terrors',
    'Makes inappropriate jokes at the worst times',
    'Is haunted by the ghosts of their forefathers',
    'Went to a boarding school for the children of middle-class wizard',
    'Finds it impossible to speak to girls',
    'Finds it impossible to speak to boys',
    'Distrusts all authority',
    'Has some pretty shady connections',
    'Fights for undead rights',
    'Once got lost in a hedge maze',
    'Lost their family in a dragon attack',
    'Is sure there is a duckbunny watching them. Somewhere.',
    'Wants to be famous, no matter what',
    'Is a complete exhibitionist',
    'Runs a small family bakery',
    'Grew up in a frozen jungle',
    'Always romanticised adventure',
    'Does not trust gold and therefor only barters goods and services',
    'Has a twin that constantly impersonates them',
    'Fought in the Blood Arenas of Manshaka',
    'Is the only surviving member of their previous adventure party',
    'Can\'t seem to hold their liquor',
    'From a line of fallen royalty',
    'Once caught 5 pints of ale, when no one was around to witness it. Or so they say',
    'Realised the importance of literacy far too late in life',
    'Has trouble going down stairs',
    'Always has to blow out and light a candle 5 times every time they leave a room',
    'Acts shallow but only to hide their insecurities',
    'Allergic to Drow',
    'Survived the plague',
    'Doesn\'t understand sarcasm',
    'Believes in racial purity',
    'Accidentally torched the local temple and is now cursed by its god',
    'Believes they have a claim to the throne',
    'Thinks they can read the future',
    'Is downright racist towards living skeletons',
    'Always speaks in the third person',
    'Was beaten and imprisoned for their religious beliefs',
    'Is terrified of rats',
    'Believes trees can speak to them and them alone',
    'Was disowned by their family',
    'Has the knowledge of the worlds funniest joke',
    'Killed a simulacrum of themselves only to realize... it was the original',
    'Is actually a Half-Fiend in disguise',
)