country = (
    'Aglarond',
    'Akanûl',
    'Aleaxtis',
    'Ammarindar',
    'Amn',
    'Amra',
    'Anok-Imaskar',
    'Ardeep',
    'Argissthilliax',
    'Aryvandaar',
    'Athalantar',
    'Axe Kingdoms',
    'Beastlands',
    'Bhaerynden',
    'Blackfeather Barrens',
    'Caesinmalsvir',
    'Calimshan',
    'Chalsembyr',
    'Chessenta',
    'Chondath',
    'Chu\'ta Te',
    'Coramshan',
    'Cormyr',
    'Daerimathlor',
    'Damara',
    'Dambrath',
    'Darastriverthicha',
    'Darastrixhurthi',
    'Deep Kingdom',
    'Delzoun',
    'Doegan',
    'Durpar',
    'Edenvale',
    'Eiellûr',
    'Elturgard',
    'Erlkazar',
    'Eskorn',
    'Esparin',
    'Estagund',
    'Evermeet',
    'Fraaszummdin',
    'Free Cities of Parsanic',
    'Free Cities of the Vilhon Reach',
    'Gharraghaur',
    'Gontal',
    'Gundarlun',
    'Halruaa',
    'Haunghdannar',
    'High Imaskar',
    'Horreb',
    'Iliyanbruen',
    'Illefarn',
    'Ilythiir',
    'Impiltur',
    'Keltormir',
    'Khazari',
    'Khuur',
    'Kingdom of Nix',
    'Koguryo',
    'Konigheim',
    'Koryo',
    'Kozakura',
    'Kultaka',
    'Kuong Kingdom',
    'Langdarma',
    'Lantan',
    'Lapaliiya',
    'Luiren',
    'Luruar',
    'Many-Arrows',
    'Meiritin',
    'Memnonnar',
    'Miyeritar',
    'Moondale',
    'Mulhorand',
    'Muranndin',
    'Murghôm',
    'Najara',
    'Narfell',
    'Nathlan',
    'Nether\'s Land',
    'Netheril',
    'Nexal',
    'Nimbral',
    'Nmalk',
    'Oghrann',
    'Olleth',
    'Orishaar',
    'Ostoria',
    'Payit',
    'Payit',
    'Petan',
    'Pezelac',
    'Ra-Khati',
    'Rangfjell',
    'Rashemen',
    'Raumathar',
    'Realm of Fire',
    'Realm of Lands',
    'Realm of Tides',
    'Relmaur',
    'Roldilar',
    'Samarach',
    'Sarphil',
    'Selmalyr',
    'Sembia',
    'Semphar',
    'Sespech',
    'Sessrendale',
    'Shadowdale',
    'Shanatar',
    'Shantel Othreier',
    'Shou Lung',
    'Silla',
    'Sossal',
    'Syòrpiir',
    'T\'u Lung',
    'Tabot',
    'Tashalar',
    'Tathtar',
    'Tethyr',
    'Tharkrixghontix',
    'Thay',
    'Thearnytaar',
    'Thesk',
    'Thindol',
    'Threskel',
    'Tuern',
    'Tymanchebar',
    'Tymanther',
    'Ulgarth',
    'Utheraal',
    'Vaasa',
    'Valashar',
    'Var',
    'The Vast',
    'Vastar',
    'Vesperin',
    'Wa',
    'Warring States',
    'Xothaerin',
    'Yaïmmunahar',
    'Yikarian Empire',
    'Zakhara',
)