eye_colour = (
    'Yellow',
    'Amber',
    'Brown',
    'Hazel',
    'Green',
    'Blue',
    'Gray',
    'Aqua',
    'Red',
    'Purple',
    'Pale Brown',
    'Pale Blue',
    'Pale Green',
    'Pale Gray',
    'Deep Blue',
    'Violet Red',
    'Orange',
    'Spring Green',
    'Sea Green',
    'Emerald Green',
)