hair_colour = (
    'Darkest brown',
    'Dark chestnut',
    'Dark brown',
    'Milk chocolate brown',
    'Dark chestnut brown',
    'Light chestnut brown',
    'Medium brown',
    'Walnut brown',
    'Caramel brown',
    'Light golden brown',
    'Mousy',
    'Light ash brown',
    'Lightest brown',
    'Maple brown',
    'Ash-blond',
    'Bleached blond',
    'Blond',
    'Dirty blond',
    'Dark blond',
    'Golden blond',
    'Honey blond',
    'Platinum blond',
    'Sandy blond',
    'Strawberry blond',
    'Reddish blond',
    'Soft-black',
    'Raven black',
    'Jet-black',
    'White',
    'Gray',
    'Red',
    'Platinum',
    'White',
    'Dark Blonde',
    'Blonde',
    'Bleach Blonde',
    'Dark Redhead',
    'Light Redhead',
    'Brunette',
    'Auburn',
    'Yellow',
    'Amber',
    'Brown',
    'Hazel',
    'Green',
    'Blue',
    'Gray',
    'Aqua',
    'Red',
    'Purple',
    'Pale Brown',
    'Pale Blue',
    'Pale Green',
    'Pale Gray',
    'Deep Blue',
    'Violet Red',
    'Orange',
    'Spring Green',
    'Sea Green',
    'Emerald Green',
    'Mald',
    'Malding',
)