skin_colour = (
    'Pale',
    'Fair',
    'Light',
    'Light Tan',
    'Tan',
    'Dark Tan',
    'Brown',
    'Dark Brown',
    'Black',
    'Gray',
    'White',
    'Gold',
    'Silver',
    'Bronze',
    'Red',
    'Orange',
    'Yellow',
    'Green',
    'Blue',
    'Purple',
    'Pale Yellow',
    'Dark Red',
    'Red-Orange',
    'Light Red',
    'Amber',
    'Olive',
    'Aqua',
    'Pale Brown',
    'Pale Blue',
    'Pale Green',
    'Pale Gray',
    'Deep Blue',
    'Violet Red',
    'Spring Green',
    'Sea Green',
    'Emerald Green',
)