title = (
    'Protector of Nightmares',
    'Admiral of Justice',
    'Patriarch of Faith',
    'Exarch of City Planning',
    'Delegate of Tourism',
    'Director of Warfare',
    'Tribune of Information',
    'Warlock of the South',
    'Abbot of the Undead',
    'Shaman of the Light',
    'Corporal of the Rivers',
    'Sultan of the Reach',
    'Headman of Ice',
    'Lord of Health',
    'Delegate of Coin',
    'Captain of Health',
    'Consul of Hope',
    'Apostle of Worship',
    'Missionary of Blood',
    'Pastor of Pure Hearts',
    'Eminence of Orcs',
    'Imperator of the Mountains',
    'Captain of Realms',
    'Delegate of Development',
    'Official of Toxins',
    'Baron of Virtue',
    'Baron of Tactics',
    'Doctor of Dreams',
    'Missionary of Misery',
    'Novice of the East',
    'Divine of Nightmares',
    'Blessed of War',
    'Cardinal of Dawn',
    'Noble of Food',
    'Official of Communication',
    'Tribune of Weapons',
    'Matriarch of the Marine',
    'Imam of Piety',
    'Angelic of the Earth',
    'Witch of the White',
    'Defender of Damned',
    'Chief of Dawn',
    'Shogun of the East',
    'Administrator of Control',
    'Overlord of Coin',
    'Lord of Sports',
    'Curator of Virtue',
    'Seer of Bones',
    'Angelic of Nightmares',
    'Reverend of Sanctity',
    'Warrior',
    'Champion',
    'Fighter',
    'Hero(ine)',
    'Soldier',
    'Combatant',
    'Conscript',
    'Trooper',
    'Enlisted',
    'Advocate',
    'Guard',
    'Guardian',
    'Paladin',
    'Partisan',
    'Protector',
    'Assailant',
    'Assassin',
    'Brawler',
    'Bruiser',
    'Duelist',
    'Gladiator',
    'Mercenary',
    'Militant',
    'Militiaman',
    'Man a',
    'Arms',
    'pugilist',
    'Scrapper',
    'Contender',
    'Tanker',
    'Warlord',
    'Hireling',
    'Spellsword',
    'Sellsword',
    'Legionnaire',
    'Activist',
    'Rioter',
    'Standard Bearer',
    'Gunner',
    'Duke/Duchess',
    'Marquis/Marquise',
    'Earl',
    'Count/Countess',
    'Viscount/Viscountess',
    'Baron/Baroness',
    'Dame',
    'Lord/Lady',
    'Emperor/Empress',
    'Tsar',
    'Kaiser',
    'Prince/Princess',
    'Knight',
    'Squire',
    'Esquire',
    'Paige',
    'Bandit',
    'Castellen',
    'Legate',
    'Centurion',
    'Constable',
    'Steward',
    'Tribune',
    'Captain',
    'Wanderer',
    'Hunter',
    'Maiden',
    'Emissary',
    'Ambassador',
    'Inquisitor',
    'Vanguard',
    'Valkyrie',
    'Brigand',
    'Keeper',
    'Warden',
    'Rogue',
    'Watcher',
    'Sentinel',
    'Outrider',
    'Herald',
    'Exile',
    'Ranger',
    'Scout',
    'Watchman',
    'Tracker',
    'Sentry',
    'Lancer',
    'Dragoon',
    'Pathfinder',
    'Commander',
    'Sergeant',
    'Commissar',
    'Huscarl/Housecar',
    'Primarch/Matriarc',
    'Sworn-Sword',
    'Majordomo',
    'Seneschal',
    'Prior',
    'Princeps',
    'Caliph',
    'Confessor',
    'Chastener',
    'Exarch',
    'Hierophant',
    'Imperator',
    'Tetrarch',
    'Cenobite',
    'Chamberlain',
    'Monsignor',
    'Praetor',
    'Adjunct',
    'Adjutant',
    'Vizier',
    'Soveriegn',
    'Dauphin',
    'Primarch',
    'Ensign',
    'Corporal',
    'Maor',
    'Landgrave',
    'Decurion',
    'Hussar',
    'Chairman',
    'Registrar',
    'Consul',
    'Midshipman',
    'Comrade',
    'Margrave',
    'Warchief',
    'Chief',
    'Chieftain',
    'Lieutenant',
    'General',
    'Admiral',
    'Vice Admiral',
    'Commodore',
    'Justicar',
    'Judge',
    'Justice/Chie',
    'Justice',
    'Commissioner',
    'Agent',
    'Marshal',
    'Bishop',
    'Archbishop',
    'Cardinal',
    'King/high King',
    'Shaman',
    'Priest',
    'Pastor',
    'Minister',
    'Einherjar',
    'Prefect',
    'Imperial',
    'Baronet',
    'Shah',
    'Shahanshah',
    'Sultan/Sultana',
    'Malik/Malikah',
    'Emir/Emira',
    'Raja/Rani',
    'Maharaja/Maharani',
    'Caliph/Calipha',
    'Padishah',
    'Khan',
    'Khagan',
    'Noyan',
    'Boyar',
    'Jarl', 
    'Viceroy',
    'the Wolf',
    'the Bear',
    'the Falcon',
    'the Hawk',
    'the Lion',
    'the Rhino',
    'the Blood Hawk',
    'the Fox',
    'the Jackal',
    'the Frog',
    'the Dire',
    'the Rat',
    'the Dragon',
    'the Shark',
    'the Elephant',
    'the Tlalusk',
    'the Wolverine',
    'the Black Wolf',
    'the Black Bear',
    'the Black Falcon',
    'the Black Hawk',
    'the Black Lion',
    'the Black Rhino',
    'the Black Fox',
    'the Black Jackal',
    'the Black Frog',
    'the Black Dire',
    'the Black Rat',
    'the Black Dragon',
    'the Black Shark',
    'the Black Elephant',
    'the Black Tlalusk',
    'the Black Wolverine',
    'the Red Wolf',
    'the Red Bear',
    'the Red Falcon',
    'the Red Hawk',
    'the Red Lion',
    'the Red Rhino',
    'the Red Fox',
    'the Red Jackal',
    'the Red Frog',
    'the Red Dire',
    'the Red Rat',
    'the Red Dragon',
    'the Red Shark',
    'the Red Elephant',
    'the Red Tlalusk',
    'the Red Wolverine',
    'the White Wolf',
    'the White Bear',
    'the White Falcon',
    'the White Hawk',
    'the White Lion',
    'the White Rhino',
    'the White Fox',
    'the White Jackal',
    'the White Frog',
    'the White Dire',
    'the White Rat',
    'the White Dragon',
    'the White Shark',
    'the White Elephant',
    'the White Tlalusk',
    'the White Wolverine',
    'the Diseased',
    'the Petulant',
    'the Lost',
    'the Shambling',
    'the Insidious',
    'the Northerner',
    'the Dark',
    'the Debased',
    'the Powerful',
    'the Doughty',
    'the Avenger',
    'the Degenerate',
    'the Invincible',
    'the Erring',
    'the Loud',
    'the Disconcerted',
    'the Dominant',
    'the Horrid',
    'the Unliving',
    'the Battle-Scarred',
    'the Dreadful',
    'the Deadly',
    'the Boastful',
    'the Jubilant',
    'the Crooked',
    'the Vicious',
    'the Dastard',
    'the Wary',
    'the Old',
    'the Smasher',
    'the Horrid',
    'the Lowbred',
    'the Marauding',
    'the Tricky',
    'the Farseeing',
    'the Judge',
    'the Mysterious',
    'the Abominable',
    'the Nauseating',
    'the Northerner',
    'the Faithful',
    'the Haunt',
    'the Enraged',
    'the Champion',
    'the Savage',
    'the Frozen',
    'the Pillager',
    'the Aged',
    'the Iniquitous',
    'the Warped',
    'the Sinful',
    'the Inbred',
    'the Overseer',
    'the Unfaithful',
    'the Tricky',
    'the Vanquisher',
    'the Reckless',
    'the Witch',
    'the Short',
    'the Queen',
    'the Cunning',
    'the Grandmaster',
    'the Novice',
    'the Alert',
    'the Oblique',
    'the Gallant',
    'the Corrupt',
    'the Relentless',
    'the Powerless',
    'the Alchemist',
    'the Daunting',
    'the Dishonorable',
    'the Tricky',
    'the Seeker',
    'the Oblique',
    'the Warmonger',
    'the Fallen',
    'the Disgusting',
    'the Kneebiter',
    'the Poltroon',
    'the Dauntless',
    'the Unconquered',
)
# Arch, Grand, Elector, Crestfallen, Hollow, Royal, Forlorn, Holy, Divine, Guilded,